variable "aws_region"               {}
variable "project"                  {}
variable "vpc_default_id"           {}
variable "bastion_public_ip"        {}
variable "bastion_private_ip"       {}
variable "security_group_node_id"   {}
variable "route53_internal_zone_id" {}
variable "bastion_rsa_key"          {type="map"}
variable "registry_bucketname"      {}
variable "enableRegistryBucket"     {}
variable "enableRegistryPush"       {}
